### ISSUE TITLE
eq and compare functions in Float aren't available

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#104]
Outside of this project, `Relude.Float.eq` doesn't exist and `Relude.Float.Eq.eq` isn't accessible. I think the same is true for Ord-related functions. Probably worth checking if this is happening to Int as well.

**Comment by andywhite37** [comment]
I added eq and compare to Float and added tests, so hopefully this should be fixed.  It's not released yet, so I'll leave this open until we verify.

**Comment by andywhite37** [comment]
Released in 0.12.0 - reopen if still an issue.
