### ISSUE TITLE
Consider making infix helpers work more cleanly in compiled JS

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#129]
Particularly, I'm thinking about `>>` here (and possibly other infix functions that work on function values). With an `open Relude.Globals`, these infix functions are accessible, but they actually require and call a `$great$great` function in the JS output, instead of being cleanly inlined, which you would expect with a compose function.

We might be able to improve this experience by offering a module that should be `include`'d (instead of `open`'d), because when the `(>>)` function is defined in the same module, it is optimized away (see [this example](https://reasonml.github.io/en/try.html?rrjsx=true&reason=DYUwLgBAFAfDCUEC80BmAaCBzTAPRSM2UqU+8A3AFBUC2A9gCYCuoEAkgHaQoDeVECKEhh6AZTAAnAJacsyCAGcpsrAH16qNbLDUAvtTpNWICBJlyF-QcIgBjetwCGsxQqgA3TMskEiAKUUAOnNVINlGEFwAeVIvJSlEGBQABn1DWwdnVwAxemZJBS4wINFQyzgzFTkgrLAXTkUoACIAFmbKGkCg4HosKDqGxTyCqABGACYAZlb4eCA)).

This would have the downside of junking up any modules where you `include Relude.Whatever` with new `let` bindings that will be exported by default. =/ So maybe not the perfect solution, but it could have the benefit of removing runtime overhead and optimizing more cleanly in the compiled JS (in addition to being easier to read). So maybe worth a try?

**Comment by johnhaley81** [comment]
This sounds like a great compiler optimization to make. Something like this should work in both cases.

**Comment by mlms13** [comment]
I don't think what I've proposed here is necessarily the answer, but the exploration going into #169 (a standalone tool or proposed option for Bucklescript that would dump all modules into a single file for a "production" build with cleaner JS output) would probably also solve this.
