### ISSUE TITLE
Look into using klipse for interactive documentation

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#130]
vikpelle from the Discord chat pointed out this tool to us:

https://github.com/viebel/klipse#reasonml-version-3

**Comment by mlms13** [comment]
I was trying to figure out if there's a way to include a library like Relude as a context in which your examples would run, and I couldn't find a clear example (but I didn't look very hard). But man, something like this would be really great.

**Comment by andywhite37** [comment]
https://codesandbox.io is another option

* does it have better support for reason now?
* can we embed editable snippets from codesandbox in our pages?
* can we create a single example project and link to specific examples?
* or is it best to just create individual examples?

**Comment by mlms13** [comment]
Just to keep this issue up-to-date, the future of sketch.sh is looking very promising. It now supports a Bucklescript backend, some work is being done to include Relude there, and embedding is a planned feature.

Even if we can't generate the embedded snippets at first, having live, runnable code would be such a huge win that I'd be happy to write a bunch of docs by hand, separately from the code/interfaces.

**Comment by mlms13** [comment]
I think I'm going to close this...

An interactive playground for Relude would be awesome, but we're probably not going to build our own. If a tool becomes available that can load and compile Reason dependencies, we'll definitely update the docs/readme with a link, but there's not a ton of benefit in keeping this ticket open while we wait.
