### ISSUE TITLE
Fix security alerts (who cares?)

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#132]
We're getting a security alert in github for a vulnerability in `marked`, which is a dependency of `docsify`, which powers the doc site.

There is a PR in `docsify` to bump `marked` to a safe version:

https://github.com/docsifyjs/docsify/pull/862

This PR is for a different issue, but upgrading `marked` will fix our security alert.

**Comment by mlms13** [comment]
The relevant PR has been closed, but there doesn't appear to be an end in sight to security alerts out of `docsify`... Maybe this is just the state of affairs in the JS world? Luckily "security alerts" for our docs website are not super important, so I vote we just ignore it.
