### ISSUE TITLE
Improve Ord

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#140]
I recently pushed a helper module with extensions for `Ord`, but it isn't complete:

- [x] Add `clamp: (~min: t, ~max: t, t) => t`
- [x] Add `between: (~min: t, ~max: t, t) => bool`
- [x] Add `abs`, which needs `Ring`
- [x] Implement for `Int`
- [x] Implement for `String`

A few more considerations:

- `clamp` and `between` seem like good candidates for needing labels, but I'm not sure if we've used labeled arguments elsewhere
- Where did we end up on things like `option` and `result` implementing Ord? Should they also get these helper functions? Maybe we should have things like `Option.Int.gte`, similar to how we have List and Array extras that are specialized for their inner type?

**Comment by johnhaley81** [comment]
WRT labelled args, something like `String.splitList` and `String.splitArray` would also be a good candidate.

**Comment by mlms13** [comment]
I added the extra Ord helpers and included them for Int, Float, and String. We could probably include them in more places if we find it useful. I didn't change `splitList` and `splitArray` as part of this, but I don't disagree that using labels to help clarify parameters of the same time could be useful.
