### ISSUE TITLE
Add `not` to Globals

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#143]
While a `not: bool => bool` function is available in Pervasives, that function is, by design, not available in Reason (at least, not by that name... it's available as `!`). Having a real `not` function can be handy for piping and composing (because `(!) << someCondition(x)` looks funny), so I think it might be a nice addition in Relude.Globals.

**Comment by johnhaley81** [comment]
I just ran into this the other days  and solved it the same way you showed up there. I agree that piping into `not` would look much cleaner.

**Comment by mlms13** [comment]
Sadly, it doesn't look like this can be done. As far as I can tell, `refmt` always turns `not` into `(!)`, which means that `not` is effectively a reserved word. :disappointed: 

For example, run this sucker through `refmt`:

```reason
let not = (!);
let isFoo = v => v == "foo";
Js.log(List.map(not << isFoo, ["foo", "bar"]));
```

**Comment by johnhaley81** [comment]
What about `inverse`?

**Comment by mlms13** [comment]
Yeah, I probably closed this prematurely... surely we can find some good name. `flip` is for function arguments and `negate` is for `Ring`, but `inverse` definitely seems like a good candidate.

**Comment by mlms13** [comment]
I went with the `inverse` name, at least for now.
