### ISSUE TITLE
Try out bisect_ppx for code coverage

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#156]
aantron has gotten his bisect_ppx code coverage tool working with bucklescript, so we should try it out.  He said that it's fairly early, so there might be some rough edges, but maybe we can help find and fix them, or at least point them out.

https://github.com/aantron/bisect_ppx#readme

https://github.com/aantron/bisect-starter-bsb#readme

**Comment by andywhite37** [comment]
One immediate challenge I see with this is that bisect_ppx wants to have a `main` executable in which to do it's thing, but jest is kind of magic in that it just discovers your tests and runs them directly in js land.  If we really wanted bisect_ppx, we might have to setup a `main` entry point (maybe using the jest API?), and then setup bisect_ppx within that.

If anyone wants to take a stab at this, I'd be very open to seeing it work, but I don't think it's something I'll likely get to anytime soon.

**Comment by kyldvs** [comment]
@andywhite37 I notice this repo used Jest bindings of some sort, is there a reason not to use [Rely](https://reason-native.com/docs/rely/)? We've got a demo repo somewhere with bisect_ppx and code coverage that I could find for you

**Comment by andywhite37** [comment]
@kyldvs - yeah, unfortunately, we are a little stuck in the js/bucklescript world at the moment.  There's no real reason for that other than we haven't undertaken the work to make the library cross-compatible with native and bucklescript.  We have a ticket #133 to explore what it would take to make the library work on native, but we haven't undertaken that yet.  We're dependent on the library bs-abstract which has a similar issue open, so it will take some work and coordination to get there.

I don't think it will be a colossal effort, but we just need to split some things out (like any of our modules that are `Js`-specific utilities), and re-implement some functions that we might currently just be aliasing things from the `Js` modules for convenience.

**Comment by kyldvs** [comment]
Cool makes sense, yeah I'd love to see this usable in native as well!

**Comment by mlms13** [comment]
Thanks @jihchi and @aantron for making this happen and for reviewing! To the point about native, we're tracking that in #133, so maybe Rely someday!
