### ISSUE TITLE
ALT instance for IO

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#189]
We should be able to add an `ALT` instance for `IO`, which would basically take two `IO` effects, and use the first one if it succeeds, or fallback to the second one if the first fails.  The key is that `io2` should only be run if `io1` fails, so we should write a unit test for that.

It might be as simple as this:

```reason
let alt: 'a 'e. (IO.t('a, 'e), IO.t('a, 'e)) => IO.t('a, 'e) =
  (io1, io2) => io1 |> IO.catchError(_ => io2);
```

A use case might be something like this:

```
let io = readFromLocalStorage <|> makeNetworkCall <|> IO.pure(hardcodedFallbackData);
```

**Comment by mlms13** [comment]
That's a big :+1: from me! I might take a crack at this later today if I get a chance.

**Comment by andywhite37** [comment]
I went ahead and added this in 0.38
