### ISSUE TITLE
Start README and documentation site

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#19]
It looks like jaredly/redoc is probably the fastest and easiest way to get API doc pages up.

**Comment by andywhite37** [comment]
We decided against using redoc, so the next one we wanted to try is: https://github.com/ostera/bsdoc

**Comment by mlms13** [comment]
I updated the README to hopefully make it a bit more approachable (no WIP warning, a simple code example). Obviously better/more documentation is still on the list of things we want to do, but the redoc-generated site is probably fine for now, at least until the community comes up with a better story for library docs.
