### ISSUE TITLE
Unfamiliar syntax in documentation for Show

### ISSUE THREAD

**Issue by alavkx** [reazen/relude#193]
While reading the docs, I've encountered some syntax that I haven't seen yet.

```ocaml
// Int show
module Int {
  module Show: SHOW with type t = int = {
    type t = int;
    let show = string_of_int;
  };
};
```

Is "`with type t = int `" how you pass a type argument to a module? Is there a name for this? 

If you feel it's complex enough to warrant a link to documentation, we should add it! Otherwise, we can add a note introducing the syntax.

Thanks for all of your hard work! ❤️

**Comment by mlms13** [comment]
Hey, that's indeed a bit of a weird one! :slightly_smiling_face: If you don't mind the OCaml syntax, the topic [is mentioned in the manual](https://caml.inria.fr/pub/docs/manual-ocaml/moduleexamples.html#sec24).

My understanding (which might be a little off) is that `module type SHOW` defines an abstract `type t;`. So when you implement `SHOW` for a specific type, that type information is hidden away inside the module. To the outside world, `Int.Show.t` is completely abstract and useless, unless you provide some extra type hints (`with type t = int`) in the signature.

I'll add this point to our "things to blog about" ticket (#175). I think @andywhite37 may have mentioned it in the post he recently wrote, and I'll try to cover it a bit more in the "intro to typeclasses using module types" article that I'm working on.

**Comment by andywhite37** [comment]
I also found this link, but it feels like this manual assumes some overall understanding of all the terminology, so it's a little hard to grok in isolation: https://caml.inria.fr/pub/docs/manual-ocaml/modtypes.html#sec220

We can add these links to the docs, but not sure they will be helpful - what do you think @alavkx ?

**Comment by alavkx** [comment]
Hm. The module types link made my eyes glaze over for the first couple reads, but I think I'm starting to get it. Those docs are defining `with type` as a "Module constraint". Is that correct? I'm a bit fuzzy why it's necessary, as the module isn't "private". The outside world has access to `Int.Show.t`, which has the type equation `t = int`. 
If the example was —
```ocaml
module Int {
  module Show: SHOW with type t = int = {
    type t; // Abstract
    let show = string_of_int;
  };
};
```
It'd make a bit more sense to me. Though, I still wouldn't get why you don't set `type t = int` directly in the module and forgo the "type constraint".

To answer your question — I don't think it'd be enough to drop the link in. With that said, linking to relevant documentation, and defining the syntax as a "type constraint" (if that is correct), is a start. It'll give people a starting point to search for things on their own if they are curious.

**Comment by mlms13** [comment]
I think the issue is that the module type is defined like:

```reason
module type SHOW = {
  type t; // abstract
  let show: t => string;
};
```

So when you create an implementation for ints:

```reason
module IntShow: SHOW = {
  type t = int;
  let show = string_of_int;
};
```

The outside world only knows that `IntShow` conforms to module type `SHOW`. Internally, `IntShow` knows that `t = int`, but the outside world just knows that `SHOW` has some abstract type `t`. I think `SHOW with type t = int` is how you tell the outside world "this conforms to SHOW, _and also_ here's some extra information about `type t`."

**Comment by mlms13** [comment]
I created a [small example](https://nit.sketch.sh/?code=LYewJgrgNgpgBAFwJ4Ad4GUASB5A6nAXjgG8AoORVeBAbnLlgTgGcALEAdwC5FCA+FggBOASwB2AczoBfOqVCRYcdOw4BRAB7CAhs0JwAFOh5Y8ASn4l6jODA0BjKNpHB9AN0voAdG04G3FgDUgXAARACE4aGksqTy4NDwAJJiCCqcJjj4RGQUyGi8ROK01jBMvhz6zMLiEgD6IABmdcUycgqJcClpqpo6ekTp6lpCugbdQ2ZyAFLMXlAgEuOpQ32jc3aOzsAGACxmZkA) demonstrating how the issue manifests itself in practice.

When we use our module `IntShow: SHOW` as a parameter to construct other modules, the functions we get back (e.g. `exclaim`) have the inferred type `IntShow.t`, and nothing outside of the `IntShow` module knows that `IntShow.t` is actually the same type as `int`, so you can't pass integer values to `IntShowExtras.exclaim`. In that example, adding `with type t = int` on line 10 will fix the compiler error.

This can definitely be a tricky thing to understand, so let me know if any of this has been helpful. I made a note in #175 to cover this in my blog post about module types, and I'll probably copy some of the examples from this issue if any of them were useful in understanding this. :smile:

**Comment by alavkx** [comment]
I now understand the module constraint, and why it's necessary. Thank you! The living example helped a ton.
