### ISSUE TITLE
Consider some changes to handling of code coverage files in git and docs

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#202]
I had the code coverage files checked-in b/c I thought it might be useful to have it stored with the code, and linked-to from the docs, but it just adds a ton of noise to releases, so maybe we should just remove it.  I guess this is the downside of having the docs in the same branch as the code.

Coveralls might deserve some attention here too, as it also doesn't add a huge amount of value, other than tracking changes to the overall coverage %, which is okay from a high-level, but not very useful for improving coverage by testing more functions.  Since we don't check-in the .bs.js files, coveralls can't really show any useful coverage details.  Maybe we can setup the `master` CI build to push all the files into coveralls - not sure how that works.

It would be nice to use a reason/ocaml-based coverage tool (bisect_ppx - #156) rather than running coverage on the js code, but that's another issue.

**Comment by andywhite37** [comment]
We might want to look into using GitHub actions #203 before we make any changes to the coveralls setup.

**Comment by andywhite37** [comment]
As mentioned in #203 - I'm going to setup GH actions to build all the reazen projects, then I'll remove all the coverage report files from Git, and just not check that stuff in anymore.

I don't know if we can pump the .bs.js files into coveralls, so I think we'll just not have the detailed coverage reports easily accessible, and just run them on demand locally when needed.  We can keep coveralls around to track the overall percentage.

**Comment by flash-gordon** [comment]
Here are instructions on how to set up deps caching: https://github.com/actions/cache/blob/master/examples.md#node---npm
I guess it will save some time

**Comment by andywhite37** [comment]
@flash-gordon - I tried adding the cache as you mentioned, and it appears to be doing a thing, but it mentioned something about not caching node_modules in the link you posted.

> Note: It is not recommended to cache node_modules, as it can break across Node versions and won't work with npm ci

Is this saying that the actions/cache thing *doesn't* cache the node_modules?  Or is it a warning that you maybe shouldn't do that?

As a side note, I'm familiar with the caching of dependencies - we're doing it now with CircleCI, and I think we are in fact caching the node_modules, but I'm not sure if I'm doing it right with GitHub actions.

**Comment by andywhite37** [comment]
In this build - the cache step seems to be getting a hit, but then the `npm install` step seems to re-install.

https://github.com/reazen/relude/commit/f7ebe01e9094dd7ae36c188e915c6c93d52085dc/checks?check_suite_id=354078134

Do I need to check for a cache hit in the `npm install` step?  It kind of seems like the cache step doesn't cache the node_modules, so maybe it's working as expected?

**Comment by andywhite37** [comment]
I think I'm not going to worry about it for now - we can improve this over time.

**Comment by andywhite37** [comment]
Everything is switched over to GH actions, and I think I've removed from git all the coverage files.  We're still using coveralls to track overall percentages, but we're no longer checking in the detailed coverage reports.

Coverage reports can now be seen locally by running `npm run coverage` and viewing the files in `/docs/coverage/...`

**Comment by flash-gordon** [comment]
I think it caches npm packages themselves so they are not re-fetched from the registry. But it’s true I didn’t test it :)
