### ISSUE TITLE
AsyncData type parameters

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#21]
@fponticelli has proposed that `Refreshing` should have it's own type parameter - but there are some other options to consider too:

```
type t('a, 'r, 'e) =
| Idle
| Loading
| Loaded('a)
| Refreshing('r)
| Failed('e)
;
```

The downside of this is that it becomes more of a bifunctor, so the basic applicative/functor/monad/etc. will only operate on the `Loaded` value, rather than on `Refreshing` too.

Another option would be to give `Loading` a value of either type `'a` or another type:

```
| Idle
| Loading('a)
| Loaded('a)
| Failed('e)
```

You can choose your `'a` to represent whatever you want, including `unit` for the first load, then something else when loaded/refreshing. the only semantic is whether the whole thing is `Loading` or `Loaded`.

Or even take it one more step:

```
| Idle('a)
| Loading('a)
| Loaded('a)
| Failed('e)
```

Or this:

```
| Idle('i)
| Loading('l)
| Loaded('a)
| Failed('e)
```

Thoughts?

**Comment by andywhite37** [comment]
Another question is whether we should "require" a `Semigroup` for the error type `'e` so we can automatically collect errors.  Maybe we could rename this to `AsyncResult` to be an async version of `Result`, and create an `AsyncValidation` with a `Semigroup` to be an async version of `Validation`?

**Comment by fponticelli** [comment]
What about:
```
type t('a) =
| Idle
| Loading
| Complete('a)
| Refreshing('a)
;
```
This addresses 2 potential problems:
* it works fine for services that cannot fail (something running in a thread for example)
* it will normally be used applying `Result 'r 'e` to `'a`

One could go a step further and have:

```
type t('a) =
| Idle
| Loading(Option 'a)
| Complete('a)
;
```

**Comment by andywhite37** [comment]
I might split the Option back out for convenience:

```
Idle
Loading
Reloading('a)
Complete('a) 
```

**Comment by andywhite37** [comment]
Basically done, let me know what you think.  I also added AsyncResult as the specialization type: `AsyncData.t(Belt.Result.t('a, 'e))` - this has map/apply/flatMap/etc. that don't require the map within map approach.
