### ISSUE TITLE
Additional data structures

### ISSUE THREAD

**Issue by austindd** [reazen/relude#233]
There is an endless world of possible data structures that would be nice to have. It wouldn’t hurt to have a curated list of desired structures/implementations, ranked by priority.

A couple off the top of my head:
- Stack
- Queue
- Hashmap (later on, a hashing library might be nice)
- MinHeap

There’s a LOT more. Obviously it’s nice to just wrap some existing implementations (Belt, Stdlib, etc.), which is fine for the short term. But internal implementations could be gradually implemented over time.

Quality control would have to be a major concern with this sort of thing. Code review is probably difficult enough without needing to verify someone’s bespoke implementation of `MinHeap.deleteMin`. But there could maybe be a requirement to implement tests for complicated data structures.

Additionally, it might not hurt to have mutable versions of some of these data structures. I know Relude is built around functional purity and immutability, but for practical purposes, it might be good to offer some mutable alternatives. One way to organize that code might be to keep it in a separate `Mutable` module, to clearly segregate them.

Just some thoughts.

**Comment by andywhite37** [comment]
I think it would be cool to make this list, but I don't think we need to get any/all of these into relude core. It's fine for these things to live outside in separate libraries. There are things in relude core now that should probably be pulled out, and it would be ideal to split the library up into more modular pieces, but that's a bigger, more grueling effort. This library doesn't need to be the gatekeeper for things. The intention is for this to be a smallish stdlib (it's not exactly small at the moment), and to allow others to use the "typeclasses" and extensions outside the lib to build other things.

**Comment by austindd** [comment]
@andywhite37 That makes sense. I suppose that's more in keeping with the "Prelude for Reason" theme. Perhaps there could be a `relude-data` library to house most of these things...

**Comment by andywhite37** [comment]
I added some data structure ideas to our "Things that don't belong here" list in #24 - @austindd - if you want to start a library of data structures, you're welcome to. You can use the name `relude-data` if you want.

I'm going to close this ticket for now.
