### ISSUE TITLE
List.fold_right type errors incorrectly... I think...

### ISSUE THREAD

**Issue by erlandsona** [reazen/relude#263]
@mulmus#4010 workin' on a transcription of `Data.Can` rn and think I found a little type bug in Relude here... 
shove this in a file.
```
type can('a, 'b) =
  | Non
  | One('a)
  | Eno('b)
  | Two('a, 'b);
let ones: list(can('a, 'b)) => list('a) = ls => {
  let go: (can('a, 'b), list('a)) => list('a) =
    (val_, acc) =>
      switch (val_) {
      | One(a) => [a, ...acc]
      | _ => acc
      };

  List.fold_right(go, [], ls);
};
```
Gives this error.
```

  126 │       };
  127 │
  128 │   List.fold_right(go, [], ls);
  129 │ };
  130 │ /* ones = foldr go [] */

  This has type:
    list(can('a, 'b))
  But somewhere wanted:
    list('a)
  The type variable 'a occurs inside can('a, 'b)
```
But if you use the fold_right from `BsBastet` it compiles fine.
```
type can('a, 'b) =
  | Non
  | One('a)
  | Eno('b)
  | Two('a, 'b);
let ones: list(can('a, 'b)) => list('a) = ls => {
  let go: (can('a, 'b), list('a)) => list('a) =
    (val_, acc) =>
      switch (val_) {
      | One(a) => [a, ...acc]
      | _ => acc
      };

  BsAbstract.List.Foldable.fold_right(go, [], ls);
};
```
Issue seems to be the module signature expecting the input type to unify with the output type. Which in our case is not true.
https://github.com/reazen/relude/blob/master/src/list/Relude_List_Instances.re#L105

**Comment by erlandsona** [comment]
I lied... didn't realize I forgot to `open Relude.Globals;` at the top of the file so I guess I was using `Pervasives.List.fold_right`, apparently 🤷‍♂️ ?

**Comment by andywhite37** [comment]
Yeah, we tend to use camel-case rather than snake-case for the relude functions (other than a few exceptions like the bastet typeclass functions like `flat_map`, so if you're using snake case, you're probably not using things from relude.
