### ISSUE TITLE
List/Array append naming

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#266]
It's a little bit awkward that we use `append` to mean "add an item to the end" in both List and Array.

```reason
let append: ('a, t('a)) => t('a)
```

While I personally find this name intuitive for the functionality we've attached to it, the fact is, Bastet (and many other fp ecosystems) use `append` as the fundamental operation of Semigroup (which has a different meaning and a different signature).

I think Cats uses `append` the same way we do, but Cats uses `combine` as the name for the Semigroup function, so there's no ambiguity.

PureScript uses `append` for Semigroup, similar to Bastet. For the "add to the end" operation, it uses the reverse of `cons`: `snoc`.

I'm not 100% sure I even have a proposal here, but it might be worth talking about the fact that it's a little awkward that `List.append` and `List.Semigroup.append` are completely different functions.

**Comment by andywhite37** [comment]
I personally like `append` for adding an item to the end, `prepend` for adding an item to the beginning, and `concat` for combining two collections. I don't think we should design the API around what the typeclass interfaces want to call things - I think we should name the top-level functions what we want, and just shoehorn the right functions into the typeclass instances. The typeclasses are not really "first class" in this language, so I don't think we need to make everything conform to what the typeclass functions are called.

**Comment by mlms13** [comment]
Yeah, I agree that I like the names we have. I think `append` meaning "add to the end" is much more intuitive than `append` meaning "combine two of the same thing".

I just feel a little uncomfortable that referring to "the append function" could mean "the semigroup function" or "the extra function provided by Relude". Honestly, I think Cats' `combine` might be my favorite name for the Semigroup function, and I'm a little tempted to propose this to Bastet. Maybe it's not worth it.

**Comment by andywhite37** [comment]
We talked offline, but I'll just record here that I'm meh on this change. I'm not opposed to it, and I think `combine` is a better name, but not sure it's worth the trouble and the breakages it would cause.

**Comment by mlms13** [comment]
Yeah, I mostly feel the same. I like that Cats and Kotlin's Arrow use `combine` for Semigroup because I think `append` makes more sense as the counterpart to `prepend`. But I'm also not sure the change is worth it, given the breaking that would need to happen.

Anyway, just thought I'd throw it out there since I've always felt a little weird about the internal inconsistency, but I'm also happy to just close this. There probably isn't any action needed.

**Comment by mlms13** [comment]
I'm going to close this as I'm not super interested in causing this break. I still have some reservations about the naming, but not so much that I'd think a breaking change of this magnitude is worth it.
