### ISSUE TITLE
Friendly Variant tags in Javascript

### ISSUE THREAD

**Issue by chrischen** [reazen/relude#279]
When I use a Belt.Result Ok/Error type in JS, the Variant is converted with human-friendly tag names. However when I use the Relude_Validation's VOk or VError types it gets converted to integer tag names in JS:

```{ tag: 'Error', value: { _0: 0, _1: 0 } }```

Is there a way to get the translation, or have it generate human-readable tag names so that it's usable on the Javascript side?

I have some more details here: https://reasonml.chat/t/relude-variants-and-interop-with-js/2480

**Comment by mlms13** [comment]
Relude's [definition of Result](https://github.com/reazen/relude/blob/master/src/Relude_Result.re#L4) is actually just an alias for the `result` type from the OCaml stdlib. It looks like [Belt defines a separate result type](https://github.com/rescript-lang/rescript-compiler/blob/master/jscomp/others/belt_Result.ml#L25).

From the Discourse thread, it looks like you're using genType, which [appears to special-case the Belt version](https://github.com/reason-association/genType/blob/v3.34.0/src/TranslateTypeExprFromTypes.re#L95). If genType is making special rules for Belt, I don't think there's much we can do to support it from the Relude side, but I'd encourage you to open an issue with genType.

**Comment by chrischen** [comment]
The regular bs.js generated file also outputs the same non-human-readable variant values in the JS side.

**Comment by mlms13** [comment]
Ah, I didn't realize that `[@genType]` maybe needs to be added where the type is defined. I have some concerns about doing that, and I've continued the conversation in the genType ticket.
