### ISSUE TITLE
Usage with genType

### ISSUE THREAD

**Issue by chrischen** [reazen/relude#280]
I'm using genType to generate typescript code instead of plain javascript. In the generated TS files it references the Relude libs like so:

```import {Bifunctor_t as Relude_Result_Bifunctor_t} from 'relude/src/Relude_Result.gen';```

In the generated bs.js file it references
```import * as Relude_Result from "../../../node_modules/relude/src/Relude_Result.bs.js";```

The Relude_Result.gen.tsx file doesn't actually exist. Is there a way to get this to work?

**Comment by mlms13** [comment]
Similar to #279, I'd encourage you to ask the genType folks about this, maybe with a small demo repository showing the problem. It'd be great for Relude to work nicely with genType, but we're just a normal library, so I'm not exactly sure what we can do here. If the genType developers identify something we can do on our end to make their tool work better with Relude, we'll be happy to consider it!
