### ISSUE TITLE
Release build is broke - thanks odoc!

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#287]
The CI build is working at this point, but the release build seems to have broken. Unclear what the fix might be...

https://github.com/reazen/relude/actions/runs/473490646

**Comment by mlms13** [comment]
It looks like the Github Action we were using to install OCaml (so we could run odoc) is using a [deprecated, insecure command](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), and that OCaml action [is archived and no longer maintained](https://github.com/fangyi-zhou/actions-ocaml).

It looks like the main Github action for installing OCaml (and opam) is [this one](https://github.com/avsm/setup-ocaml), but it might not support OCaml 4.06.1, which our script was using. We could try upgrading to 4.08, but iirc that isn't the version that Bucklescript uses, so I assume all sorts of things would break in confusing ways. This whole ecosystem, man...

**Comment by mlms13** [comment]
I think we did a big overhaul of the whole CI pipeline as part of the v2/melange push, and since we have a working CI, I think it's safe to say this is fixed.
