### ISSUE TITLE
Bump bastet from 1.2.5 to 2.0.0

### ISSUE THREAD

**Issue by gregberns** [reazen/relude#299]
I'm really new to OCaml/Reason, and was trying to get relude, bastet, and [melange](https://github.com/melange-re/melange) working together. It appears there is a fix in bastet to support OCaml 4.12 (See: [Add support for OCaml 4.12](https://github.com/Risto-Stevcev/bastet/pull/33)), and melange requires 4.12.

Looks like bastet was updated to 2.0.0 in Feb.

**Comment by mlms13** [comment]
Yes indeedy, and we actually had a PR to bump that version open: #293

I just merged it, and I'll try to remember to make a new Relude release after work today. Thanks for the reminder! 👍
