### ISSUE TITLE
RemoteData-like type

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#3]
Does this belong in this project, or is it best to leave it in a separate lib?

The benefit of having something like that in this project is consistency with our other conventions.

**Comment by mlms13** [comment]
I like the idea of having a version of this under our control (so that we can have the flexibility to not depend on `bs-json`, for example). Feels maybe like it should be a separate repo in the `reazen` org, instead of part of our prelude, though. Thoughts?

**Comment by andywhite37** [comment]
Yeah, `RemoteData` does seem like something that maybe doesn't belong in the Prelude.  I think a separate repo makes sense.

**Comment by fponticelli** [comment]
I actually object ... the problem with `RemoteData` is in the name. I feel like `AsyncData` or something similar would fit better and make it even more generic in intent. A process on a thread might very well use that data payload. For me it should exist in core :)

**Comment by andywhite37** [comment]
Yeah, `RemoteData` is really not a great name.  `AsyncData` sounds good to me.  Maybe the type and related Functor/Applcative/Modad stuff belongs in core, but networking/etc. implementations that use the type live in external libs.

**Comment by mlms13** [comment]
Sold. I've never really liked the name `RemoteData`. Also, what do we think about a version of `AsyncData` that includes a `Refreshing(lastKnownData)` constructor?

**Comment by fponticelli** [comment]
That is interesting ... what about a constructor of `Loading(progress)`?

**Comment by andywhite37** [comment]
`AsyncData` type is started.  It could probably use some more love.

**Comment by andywhite37** [comment]
Closing this for now.  We can use other issues for further discussion.
