### ISSUE TITLE
Add min/max to Foldable.Ord

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#30]
When the outer thing is Foldable and the inner thing has Ordering, `min` and `max` should come for free. This is mostly useful for `Int` and `Float`.

**Comment by arecvlohe** [comment]
So what is this "should come for free?" I am a typeclass noob so not up on how this actually works internally or why it applies.

**Comment by mlms13** [comment]
I think a function like `let max: list('a) => option('a)` is the perfect example for understanding how typeclasses bring functionality "for free" so here we go. :smile: 

The `max` function depends on two typeclasses. The container type (e.g. `list`, `array`, some kind of custom tree structure, etc) should be a member of the `Foldable` typeclass, meaning it should have a `foldLeft` function (or `reduce` in JS speak). The inner, contained, type (e.g. `int` in the type `list(int)`) should be a member of the `Ord` typeclass, meaning that two values of that type can be compared to determine if the first is equal to, greater than, or less than the second.

We can represent these typeclass definitions as Reason module types:

```reason
module type Foldable = {
  /**
   * A type that is foldable should hold some other type ('a) inside of it.
   **/
  type t('a);

  /**
   * A type that is foldable should implement a `foldLeft` function, which converts
   * a `t('a)` into a value of some type `'b`. It does so by taking an initial value of
   * type `'b` and a "reducer" function that returns a new value of type `'b` given
   * the current value of type `'b` (accumulator) and a value of type `'a` (current).
   */
   let foldLeft: (('b, 'a) => 'b, 'b, t('a)) => 'b;
}
```

Right now our `Foldable` is just types, no implementations. But we can make `list` a member of `Foldable` pretty easily by providing a list-specific implementation:

```reason
module ListFoldable: Foldable with type t('a) = list('a) = {
  type t('a) = list('a);
  let foldLeft = (reducer, init, lst) => Belt.List.reduce(lst, init, reducer);
};
```

Here we're using `Belt.List.reduce` (with argument order swapped around), but we could have provided our own implementation or used `List.fold_left` from the OCaml stdlib. The result is the same... we now have a module that satisfies our definition of `Foldable` for the `list` type.

Next up, the `Ord` typeclass is pretty straightforward:

```reason
type ordering = GT | EQ | LT;
module type Ord = {
  type t;
  let compare: (t, t) => ordering;
};
```

And a simple implementation for `int`:

```reason
module IntOrd: Ord with type t = int = {
  type t = int;
  let compare = (a, b) => a > b ? GT : a < b ? LT : EQ;
};
```

Now the fun part, where we write functions that use these typeclasses:

```reason
/**
 * `FoldableExtras` is a module parameterized by another module (a module
 * functor in OCaml-speak). In order to use things defined in `FoldableExtras`,
 * you need to first construct it by passing in a `Foldable` implementation.
 **/
module FoldableExtras = (F: Foldable) => {
  module OrdExtras = (O: Ord) => {
    let max = data =>
      F.foldLeft(
        (acc, curr) =>
          switch (acc) {
          /* curr is the new "max" when no previous max */
          | None => Some(curr)

          /* when `curr` is greater than the existing `max`, it becomes the max */
          | Some(existing) when O.compare(curr, existing) == GT => Some(curr)

          /* otherwise the existing max is unchanged */
          | existing => existing
          },
        None, /* we start with `None`, which will be the value when the Foldable is empty */
        data
      );
  };
};
```

So we still had to write one implementation of `max`, but we did so in terms of `Foldable` and `Ord` instead of `list` and `int`. Now any foldable container type and any order-able inner type can use this same implementation of `max`. If you have an `array` of `float`, you can use this same `max` function "for free" by providing `array`'s Foldable implementation and `float`'s Ord implementation.

**Comment by mlms13** [comment]
Sorry, that was the mega-answer... I've been brainstorming up a blog post about the how and why of typeclasses in Reason, and I took this opportunity to write down an initial draft. :stuck_out_tongue_closed_eyes:

I have a couple other issues to work on like #26 and #34 that get us slightly closer to where we want to be, typeclass-wise. Some of the things spec'd out there might not be completely possible in OCaml, but that at least clarifies (hopefully?) our goal with this stuff.

**Comment by arecvlohe** [comment]
Thanks for the thorough explanation! It makes a lot more sense now. I now see how you "get this for free." Much appreciated!
