### ISSUE TITLE
Tuples - Add fst, snd functions to extract values

### ISSUE THREAD

**Issue by gregberns** [reazen/relude#303]
Haskell has Tuple functions `fst`, `snd` to extract the first and second values from the tuple. I'm not seeing it in the docs.

Signatures:

`fst :: (a,b) -> a`

`snd :: (a,b) -> b`

Would probably want to add it to all the tuple types: `Tuple3.third :: (a,b,c) -> c`

**Comment by jihchi** [comment]
It is built-in in ReasonML, see the [doc](https://reasonml.github.io/api/Pervasives.html#6_Pairoperations).

**Comment by gregberns** [comment]
Duh ... silly me. Any thoughts on adding `third`, `fourth`, etc for the tuple variations?

**Comment by johnhaley81** [comment]
Looks like this was done in #305
