### ISSUE TITLE
Fix up string replacement

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#31]
1. Rename `String.replace` to `String.replaceFirst`
2. Add `String.replaceAll`, possibly using Elude as a model

**Comment by arecvlohe** [comment]
Can I help with this one? 😅

**Comment by andywhite37** [comment]
@arecvlohe we welcome all PRs!  Please feel free

**Comment by arecvlohe** [comment]
Cool!

**Comment by andywhite37** [comment]
Thanks for the PR!  :+1:
