### ISSUE TITLE
Result.fold and Option.fold disagree about param order

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#32]
- `Result.fold` expects the `Ok` handler to come first and the `Error` handler to come second.
- `Option.fold` expects the `None` handler to come first and the `Some` handler to come second

I think i like providing the "bad case" handler first, but I don't have a super strong opinion. Either way, this should probably change to be more consistent.

**Comment by arecvlohe** [comment]
I would expect the bad case handler to come first as well. So I agree with you on that front.
