### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#34]
I forget how close we actually got to this, but the following code kind of outlines how I'd like typeclasses to work:

```
Foldable.max((module List.Foldable), (module Int.Ord), [ 3, 1, 7, 2 ]);
Foldable.maxBy((module Array.Foldable), Int.compare, [| 4, 6, 1 |]);

List.max((module Float.Ord), [ 3.1, 3.6, 4.2 ]);
List.maxBy(Float.compare, [1.2, 1.1, 1.0]);

List.Int.max([1, 2, 3]);
```

With that same pattern extended to Functor/Applicative/Monad/Traversable and all of the implementation types.

To summarize: structure things as if modular implicits were a thing, then build specialized modules since the implicit resolution isn't real yet, and possibly more specific sub-modules so you don't have to pass modules anywhere if you don't want to.

Not saying this is a radical departure from what we've already been doing... just wanted to formalize it a bit more.

**Comment by andywhite37** [comment]
:+1: from me - I like the idea to act like modular implicits exist, but have convenient, sensibly-named alternatives for each function.

**Comment by mlms13** [comment]
For the very first example:
```reason
Foldable.max((module List.Foldable), (module Int.Ord), [ 3, 1, 7, 2 ]);
```

...it's looking like this might not be possible in Reason/OCaml. I could absolutely be wrong, but I don't think there's a way to define a function that gets called with a module that has a type parameter (e.g. `Foldable.t('a)`.

We _should_ be able to define a `module FoldableOrd` that needs an outer `Foldable` and an inner `Ord`, though, and then we could have min/max functions like:

```reason
max((module FoldableOrd(List.Foldable, Int.Ord), [3, 1, 7 2]); /* Some(7) */
min((module FoldableOrd(List.Foldable, Int.Ord), [3, 1, 7 2]); /* Some(1) */
```

But maybe that's too clunky to be worthwhile? Anyway, I'll keep playing around with this. I'm not sure what the final implementation will look like, but I'm pretty confident that:

- we can share the same `max` implementation for `list(int)`, `array(float)`, etc
- "downstream" functions like `List.Int.max` and `Array.float.max` won't need to change, even if we tweak how we do the module stuff at the `Foldable`/`Ord` level... which is kind of the whole point :grinning:

**Comment by mlms13** [comment]
OK, this was good to think about, and it's basically done in #57. `min`/`max` will come with #30, and `Array` will reuse all of this in #27.

Sadly, you'll never be able to use `Foldable.max` as a function because as I mentioned above, there's no way to pass a module implementing `Foldable` as a first-class module to that function due to its polymorphic nature and the lack of true HKTs.

But the rest should all work correctly (`List.maxBy`, `List.max((module...))`, `List.Int.max`, etc) with the structure that's been set up in #57.
