### ISSUE TITLE
Remove redoc and redoc-generated documentation

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#37]
I'm having trouble with nixos and redoc stuff, and since we are planning to switch from redoc to something else anyway, I'm going to just remove redoc from the package.json, the docs folder, the current gh-pages site, etc.

(If we were planning on staying on redoc, I would have tried harder to fix my local setup :smiley:)

**Comment by arecvlohe** [comment]
What is a good alternative? Maybe going with Reason's setup would be ideal.

**Comment by mlms13** [comment]
I get a bit lost in the world of redoc/bsdoc/odoc/ocamldoc. It would be nice to find a strategy that integrates cleanly with Docusaurus, but I'm not sure such a thing currently exists. I think it was @ostera who suggested bsdoc, which looks like a nice option that uses mli/rei files with docblock comments. If we could find a way to plug that into a Docusaurus site, it might be the dream?

**Comment by arecvlohe** [comment]
Hmmm, I need to look at Docusaurus, haven't looked at it at all. Maybe there is a way to plug it all together like you said

**Comment by mlms13** [comment]
Redoc is back for now, and @jdeisenberg has been working on some docs. We may revisit this decision if/when the Bucklescript community comes up with a standardized approach to docs.
