### ISSUE TITLE
Versioning strategy

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#40]
We should discuss a versioning/release strategy.

Although it's not required, it's probably smart to push releases to npm, https://redex.github.io, or whatever other places people push ReasonML projects.

Idea for a basic process:

1. Follow semantic versioning principles and version naming conventions
1. Merge PRs/changes/etc. directly into `master`
1. When we have a set of features/fixes we want to release:
    1. make sure we have a good CI build (see #39)
    1. determine whether it's a major/minor/patch update
    1. Use the following commands to bump the version and publish the project:

```
> npm version major|minor|patch
> npm publish
> submit a PR to redex (details TBD)
```

@mlms13 - thoughts?

**Comment by andywhite37** [comment]
One thing that might be interesting to try would be to flag PRs with a `major`|`minor`|`patch` label, so that we can easily tell what type of version bump is needed.  I guess that will take us out of `v0.x` land pretty quickly... or maybe we could just treat all major updates as minor while we're still in `v0.x`.

**Comment by mlms13** [comment]
I think the redex PR only needs to be done once, initially, then it picks up on new deployments to npm automatically. I also think that in semver, breaking changes are ok in "minor" version numbers if the project version < 1.0.0 (but I could totally be wrong).

I think it would be kind of nice have a single release script that does the `npm version ...` (including a git tag) and `npm publish` only if CI says we're in good shape. I don't really know what that looks like, but I'm sure we'll figure it out. :stuck_out_tongue:

**Comment by andywhite37** [comment]
re: redex - I get it now - I never read their documentation.

For a the CI build, I think would potentially set it up to automatically version and tag successful builds, but we'd need some way to indicate which type of version bump to do for each build.  It would be cool if we could set that up, but I think it would require some manual intervention at some point, like tagging the PRs or requiring some metadata in commit messages.  I'm not sure if I like tagging the PRs, because it's disconnected from the actual code and commits, but we can brainstorm.

For step one, maybe we should setup a CI build and a small `publish` script that does the versioning/tagging/publishing, which we can run at any time we want to make a release.

**Comment by arecvlohe** [comment]
Yeah, it would be nice if there was some code checker that could derive the type of version bump.

**Comment by andywhite37** [comment]
I'm going to call this done for now.  I think manually making releases using the github releases thing is good enough for now.  Until we hit 1.0, we can just choose arbitrary minor/patch version bumps, then we'll have to get more serious.
