### ISSUE TITLE
Relude.Option.Infix.(>>=) is flipped

### ISSUE THREAD

**Issue by msvbg** [reazen/relude#47]
`Relude.Option.Infix.(>>=)` appears to have its arguments in the wrong order, at least compared to what I'm used to.

```haskell
$ ghci
Prelude> Just 5 >>= \n -> Just $ n + 1
Just 6
```

```reason
> Relude.Option.Infix.((n => Some(n + 1)) >>= Some(5));
Some(6)
```

**Comment by andywhite37** [comment]
Ah, yeah, you're right, I'll fix that.  I think we originally had the right order, but we made a change to make the `flatMap` function be "function-first" and `bind` to be "function second" but the `>>=` didn't get switched to `bind` at that time.
