### ISSUE TITLE
Surprising result from Relude.Array.drop and Relude.Array.take

### ISSUE THREAD

**Issue by jdeisenberg** [reazen/relude#49]
Is this the expected behavior, especially from `drop`?

```
take(-1, [|100, 101, 102|]) == Some([| |]);
take(-2, [|100, 101, 102|]) == Some([| |]);
take(-3, [|100, 101, 102|]) == Some([| |]);
take(-4, [|100, 101, 102|]) == Some([| |]);
```
but...
```
drop(-1, [|100, 101, 102|]) == Some([|102|]);
drop(-2, [|100, 101, 102|]) == Some([|101, 102|]);
drop(-3, [|100, 101, 102|]) == Some([|100, 101, 102|]);
drop(-4, [|100, 101, 102|]) == Some([|100, 101, 102|]);
```
I would expect all of the above to return `None`.

After looking at the code: it appears that `take()` and `drop()` call JavaScript’s `Array.Prototype.slice()`, which gives these exact weird-seeming results.

**Comment by jdeisenberg** [comment]
The same sort of thing occurs with `splitAt`:
```
splitAt(-1, [|100, 101, 102, 103|]) == Some(([], [ 103 ]))
splitAt(-2, [|100, 101, 102, 103|]) == Some(([], [102, 103 ]))
```

**Comment by andywhite37** [comment]
Yeah, I never thought about what those functions should do with a negative input.  It would be nice to eliminate the possibility of using a negative argument via the type system, but I'm not sure if it's worth using a `Nat` type there.  Returning `None` is an option too, but I'm not sure if I like the semantics of that, although maybe it's better than returning what those functions do now.

**Comment by jdeisenberg** [comment]
I’m documenting them as they are now, and wow, does it make the explanations a lot of fun to write. :) I think `Nat` is overkill; `None` is a perfectly reasonable result when giving a value that is out of bounds.

**Comment by andywhite37** [comment]
I'd be happy to explain that behavior as "the result is undefined for negative inputs at this time."  I don't think we need to justify it.

**Comment by mlms13** [comment]
My only contribution to PureScript was making `drop` and `take` behave the same with negative numbers as they do with `0`, so I'm all for this change. :)

**Comment by jdeisenberg** [comment]
I can’t even.
```
Js.log("list drop/take");
Js.log(Relude.List.drop(-1, [100, 101, 102]) == None);
Js.log(Relude.List.drop(-2, [100, 101, 102]) == None);
Js.log(Relude.List.drop(-3, [100, 101, 102]) == None);
Js.log(Relude.List.drop(-4, [100, 101, 102]) == None);
Js.log(Relude.List.take(-1, [100, 101, 102]) == Some([]));
Js.log(Relude.List.take(-2, [100, 101, 102]) == Some([]));
Js.log(Relude.List.take(-3, [100, 101, 102]) == Some([]));
Js.log(Relude.List.take(-4, [100, 101, 102]) == Some([]));
```

**Comment by mlms13** [comment]
I think this is all fixed with your recent PR, right @jdeisenberg? Feel free to reopen if that isn't the case.

**Comment by jdeisenberg** [comment]
Yes, it would seem so.
