### ISSUE TITLE
Attempt to use a normal (non-polymorphic) variant for Ordering

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#63]
bs-abstract uses a polymorphic variant for ordering:  https://github.com/Risto-Stevcev/bs-abstract/blob/master/src/interfaces/Interface.re#L130

It would be useful to understand why a polymorphic variant was used, rather than a non-polymorphic variant like:

```
type ordering = | EQ | LT | GT
```

Since `ordering` is not likely to be extended, I'm not sure what the reason was for using polymorphic.

We could deviate from bs-abstract if we wanted to, but it would be nice to keep a compatibility layer if we do.

**Comment by andywhite37** [comment]
I asked here:  https://github.com/Risto-Stevcev/bs-abstract/issues/12

**Comment by texastoland** [comment]
Another use case for polymorphic variants besides extension is making an abstract type with public tags. That doesn't seem relevant here, though.

**Comment by andywhite37** [comment]
Yeah, the public tags is actually not something to ignore... it is quite convenient.

**Comment by andywhite37** [comment]
I'm going to close - a very thorough and compelling explanation was made in the bs-abstract issue in favor of poly variants, so I suggest we stick with them!
