### ISSUE TITLE
Release script

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#64]
Talking to @mlms13 - I think we decided on a basic release procedure.  We're going to just do releases by hand for now, until we have a good procedure for doing automatic CI releases.

```bash
> ./release <bump>

where <bump> is major|minor|patch
```

This would perform the following operations:

```bash
...developer manually updates CHANGELOG.md to add summary of changes
...or maybe we can generate the changelog via PR metadata since the last tag?
...getting the new version # at this point might be tricky

# Update the version number in package.json and create the git tag
npm version $bump
npm publish

# Push the tags to the root repo
# Note: try to use an explicit reference to the root repo, rather than `upstream`
git push upstream --tags

# Create the github release
...Use github API to create a release for this new version
or
echo "Create github release now"
```

**Comment by mlms13** [comment]
Some other things that have come up or are worth thinking about:

- Would be cool if we could generate the CHANGELOG from commit messages using something [like this](https://github.com/CondeNast-Copilot/atjson/tree/latest/packages/%40atjson/conventional-changelog-emoji)
- Maybe make sure there are no uncommitted changes up front?
- `--follow-tags` seems to be the accepted way to push both commits (assuming `npm version` generates a new commit) and _annotated_ git tags (instead of `--tags`)

**Comment by mlms13** [comment]
On more thing to consider, we'll probably want to make sure we poke the `package-lock` before releasing, to make sure its versions are all up-to-date with the `package.json` (especially the top-level Relude version). Maybe `npm version` does this automatically?

**Comment by andywhite37** [comment]
I checked, and it looks like `npm version major|minor|etc` does in fact create annotated tags, so `--follow-tags` should work.

Below is a pseudo-code bash script (untested).  One thing to think about is how the script might handle cases where it bails early.  Maybe each step that creates something (commit/tag/etc.) should check to see if it has already been done, and skip it, so we don't end up creating extra versions, etc.  This might mean we would pass version numbers rather than `major|minor|etc` to the script?

```
#! /usr/env/bash

# Bash strict mode (failed commands and pipe operations abort the script, etc.)
set -euo pipefail

# Get bump type (major|minor|patch/etc.)
bump=$1

# Remove node_modules for a clean install
rm -rf node_modules

# Install and poke package-lock.json
npm install

# Make sure working dir and index are clean
# e.g. the `npm install` above might have updated the package-lock.json - abort if this happened
# TODO: Is there a better way to do this?  Does this even work?
git diff --exit-code
git diff --cached --exit-code

# Run tests
npm run test

# Generate CHANGELOG entry
# TODO
# update_changelog

# Update version in package.json, package-lock.json, create a git commit for the version, and create an annotated git tag for the version (e.g. v0.11.0)
npm version $bump

# Publish new version to npm
npm publish

# Push the commit and tag to upstream and origin (assuming we are running this from a fork)
# TODO: might want to use literal remote URLs, rather than aliases here
git push upstream --follow-tags
git push origin --follow-tags

# Create a github release via the github API
# TODO
# create_github_release
```

**Comment by andywhite37** [comment]
BTW - I will get serious about commit messages and clean git history if we find a tool that will work to generate a changelog.

**Comment by andywhite37** [comment]
Just to jot this down, here is what I'm currently doing, and it hasn't been complicated enough to justify a script so far:

```
> npm run releasebuild
> npm version major|minor|patch
> git push origin --follow-tags && git push upstream --follow-tags
> npm publish
```

**Comment by andywhite37** [comment]
I'm going to close this, as I don't think there's a pressing need for this at this point.
