### ISSUE TITLE
Add immutable Set/Map

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#70]

**Comment by johnhaley81** [comment]
Could this possibly re-wrap the `Belt.Map` implementation?

**Comment by andywhite37** [comment]
Yeah, I was thinking that we could just alias and add some stuff onto `Belt.Set` and `Belt.Map`, kind of like what we did with `Belt.Result`.

I haven't used `Belt.Set/Map` much - are they lacking anything obvious?

**Comment by johnhaley81** [comment]
I don't think so. I've used them a bunch and it can be funky to make a custom one but it's pretty fast and straightforward
