### ISSUE TITLE
Improve the `open Relude` experience by importing commonly-used modules/functions/types/etc.

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#71]
E.g. the `>>` and `<<` composition operators just work on functions, so there is little chance of collision across types.

**Comment by johnhaley81** [comment]
A note on this. There is the `Relude.Js` module which makes it so that you can access the global `Js` module when you do `open Relude`. Maybe `Relude.Js` should include everything in the global `Js` module? Or be named differently?

**Comment by mlms13** [comment]
The other thing that's currently problematic with `open Relude` is that we shadow `Js` in that case, which makes it hard to work with existing `Js` modules from Bucklescript. The new ReasonReact-with-hooks release seems to expect to use `Js.t` objects, which can't be resolved if you've added an `open Relude` above your React component definition.

This would push the change into "Major" territory, but it might be nice to hide JS-related utilities behind `ReludeJs`, possibly even in a separate repository. As a longer-term goal, this would help the core of Relude not depend on Js, so it could someday be used for native as well.

**Comment by mlms13** [comment]
@johnhaley81 beat me to it :grin:

**Comment by johnhaley81** [comment]
I'm dying :D :D :D

**Comment by andywhite37** [comment]
My personal feeling is that we shouldn't encourage people to `open Relude` since it's our main "namespace" module where we expose everything.  I would rather see a more focused module for the purpose of using `open` like a `Relude_Open.re` module which exposes all the stuff we'd want in a global open, and you'd then do `open Relude.Open` or something like that.  Maybe `Globals` would be a better name?

I don't want to have to artificially rename common things like `Relude.Js` just because it creates a conflict if some does `open Relude`.

The `Open` module could expose all the relude modules as `RList/RString/RJs` etc. so they don't conflict.

Any thoughts on that?

**Comment by andywhite37** [comment]
As far as moving all the Js stuff out of relude core, I'm in favor of that idea as a concept, but I'd like to hold off on that until someone has a real native project to work with, where we are not compiling to JS, to make sure the work is done with the right platform for testing builds/etc.  For now, I don't want to create the explosion of sub-libs until we have a good reason to do that.

**Comment by mlms13** [comment]
I actually kind of like the fact that `open Relude` shadows things like `List` and `String` and `Array`, since I think we provide a pretty decent replacement for those modules. That said, it's not too much more work to do:

```reason
module List = Relude.List;
module String = Relude.String;
```

Longer term, I think it'd be cool if Relude was complete enough to use it like `import Prelude` in PureScript, but I'm not sure how that would work with shadowing so much of OCaml's `Pervasives`, since it seems like `Pervasives` can't be turned off.

**Comment by andywhite37** [comment]
If you guys are okay with it, I would rather try out this idea in a separate `Relude.Open`/`Relude.Globals` module and not try to make `open Relude` the recommended way to use the library.  My main concern is that if we try to make `Relude.re` include the entire set of modules and also work nicely with a global `open Relude`, it's going to become an annoying juggling act between what is getting shadowed, what functions to expose globally, etc.  I think I like the name `Globals` over `Open`, so I'll go with that initially.  Ultimately, a global open is never going to satisfy everyone's needs, but we can put the truly core/common stuff in there.

I can create the initial module with something like this, and we can add stuff to it as we find things that almost everyone would just want to be globally available.

`Relude_Globals.re` (pseudocode)

```reason
module List = Relude_List; // alias List b/c we purposelly want to shadow the stdlib List
module Array = Relude_Array;
module Result = Relude_Result;
module Option = Relude_Option;
module RJs = Relude_Js;

let (>>) = Relude_Functions.(>>);
let (<<) = Relude_Functions.(<<);
```

Any other things to include initially?

**Comment by mlms13** [comment]
- I like `Globals` as a module name
- I think it makes sense to at least start with a curated set of things that are intended to be opened globally
- `Relude_String` is at a pretty stable/complete point, but other than that, I think what you have looks good.

So :+1: from me.
