### ISSUE TITLE
Js.Json helpers

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#78]
Wow, the Js.Json API is pretty miserable.  We should add some basic helpers like `isNull` and other things to help with dealing with Js.Json.t values.

**Comment by johnhaley81** [comment]
What do you think about making a `Relude.Json.Decode` and `Relude.Json.Encode` submodules where the `Decode` pulls in `bs-decode`?

**Comment by andywhite37** [comment]
Yeah, I was thinking it would be nice to have some built-in decoding stuff, or at least low-level helpers for dealing with raw Js.Json stuff.  It probably makes sense to keep bs-decode outside the core library, since it's more of a specific thing, but maybe we can build some machinery in relude core to let you plugin custom encode/decode functions.

**Comment by andywhite37** [comment]
Initial version of "basic" `Json` API released in v0.9.0 - see `Relude.Js.Json`
