### ISSUE TITLE
Small helper functions to add

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#79]
I don't want to create a million issues for little things, so here is a running list of things to add when anyone has time:

- [x] `List`/`Array` (`Foldable`?) `filterNot` - like filter, but with condition reversed
- [x] `AsyncData.eqBy` with `eq` function for inner `'a`
- [x] `AsyncResult.eqBy` with `eq` functions for both `'a` and `'e`
- [x] Add `id`, `const`, and `flip` to `Relude_Globals`

**Comment by mlms13** [comment]
PR incoming with these changes.

**Comment by mlms13** [comment]
Closing, since the functions listed here have been taken care of.
