### ISSUE TITLE
Project organization

### ISSUE THREAD

**Issue by andywhite37** [reazen/relude#92]
I just wanted to jot down some thoughts on how we could organize the project going forward.  I like the `data` and `classes` approach, but since almost everything in relude could theoretically go in `data`, I'm not sure if we'd want to put most things in there.  `classes` might also create confusion w/ hardcore FP (haskell) folks b/c they might expect to find type classes (aka `module type`s) in there, when `Foldables` and `Monads` are more like "extensions" you can add when you have an instance of a certain type class.

I wonder if there is any way we can bake the `Foldables` type stuff directly into the modules/module types for the `Foldable`/`Monad` typeclass.  I need to look at how those are setup again to understand the chicken and egg nature of it.

Anyway, another idea might be to put everything at the top level, but allow modules to put extra stuff in their own little folder.  I kind of like this setup, b/c it follows the names of the modules, and creates a nice hierarchy.

E.g.

```
# Put all the extra array stuff in an ./array folder, but put the main module at the root?
./array/Relude_Array_*.re
./Relude_Array.re
./Relude_Array.rei

# Put all the extra list stuff in a ./list folder
./list/Relude_List_*.re
./Relude_List.re
./Relude_List.rei

# Js stuff
./js/Relude_Js_Console.re
./js/Relude_Js_Exn.re
./js/...
./Relude_Js.re

# Date time stuff?
./instant/Relude_Instant_LocalDate.re
./Relude_Instant.re

etc.
```

I'm not sure where `Relude_Foldables` and `Relude_Monads` end up in this structure.  `bs-abstract` calls those things `Functions` (and we also call the module `Functions` inside those modules), which is okay, but doesn't quite capture what's going on.  At one point we had them in a folder `addons`, but that also doesn't feel quite right.

**Comment by mlms13** [comment]
Sort of related: I've been considering renaming `module Functions = (F: FOLDABLE) => ...` to `module Make = ...` which I think might be the more OCaml-y convention? But I'm not strongly committed one way or another.

That doesn't really answer any questions about where these modules should live, though. I considered naming the `classes` folder `typeclass_extensions` or `typeclass_functions` for the reasons you mentioned, but I dislike underscores.

I agree that it might make sense to do away with the `data/` folder because _everything_ could probably end up there, which doesn't do much good. Ultimately none of the folders actually matter for anything, so it's kind of up to us.

**Comment by andywhite37** [comment]
I like the `Functions` => `Make` idea, and that does feel ocamly.

**Comment by mlms13** [comment]
I wonder if it makes more sense to name the file something like `FoldableExtensions.re` or `FoldableExtras` and have an inner module that is `module Make = ...`. Then it's like you're "calling" `Make` with the bits of functionality you already have to construct a collection of utility functions.

But `Foldables.Functions(MyFoldableInstance)` is fine too.

**Comment by andywhite37** [comment]
I like `include FoldableExtensions.Make(Foldable)` - that makes sense to me

**Comment by andywhite37** [comment]
Here is a final proposal, which I think @mlms13 is on board with (based on chatting):

```
./array/Relude_Array_.*re
./list/Relude_List_*.re
./js/Relude_Js_*.re
./extensions/Relude_Extensions_Foldable.re
./extensions/Relude_Extensions_Monad.re
./Relude_Array.re
./Relude_Array.rei
./Relude_List.re
./Relude_Js.re
./etc.
```

Higher-level modules can bring in the lower-level ones via aliases.

All modules can be aliased in `Relude.re` to match the structure above, e.g.

`Relude.re:`

```
module Array = Relude_Array;
module Js = Relude_Js;

// we can define these namespace modules inline if we don't want to create the `Relude_Extensions.re` module
module Extensions = {
  module Monad = Relude_Extensions_Monad;
  module Foldable = Relude_Extensions_Foldable;
};
```
