### ISSUE TITLE
NonEmpty improvements

### ISSUE THREAD

**Issue by mlms13** [reazen/relude#97]
- [ ] Add `uncons: NonEmptyList.t('a) => ('a, list('a));`
- [x] `include` some of the typeclass modules for parity with List/Array (e.g. right now there's no `NonEmptyList.append` function without digging it out of `SemigroupAny`)
- [x] We could probably include some of the Foldable and Monad helpers

**Comment by mlms13** [comment]
It probably also makes sense to add this to `Relude.Globals`. Assuming `Relude.Globals` is getting globally opened in downstream projects, how do we want people to access NonEmptyList?

```reason
open Relude.Globals;

NonEmptyList.(make("foo", ["bar", "baz"]) |> map(String.toUpperCase));
NonEmpty.List.(make("foo", ["bar", "baz"]) |> map(String.toUpperCase));
List.NonEmpty.(make("foo", ["bar", "baz"]) |> map(String.toUpperCase));
```

**Comment by andywhite37** [comment]
Yeah, that's a good question.  We have `NonEmpty` in globals, so you should be able to use `NonEmpty.List` now, but I see the value in aliasing it to `NonEmptyList`/`NonEmptyArray` (or even `Nel`/`Nea`?).  I don't think I would vote for `List.NonEmpty`, (even though it's kind of clever), since it kind of flips the way the modules are actually setup in the code.

**Comment by mlms13** [comment]
Yeah, other submodules in `List` (like `List.String`, etc) generally tell you about the thing _inside_ the `list`, so `List.NonEmpty` would probably be confusing. I totally missed that `NonEmpty` was already in Globals, which is good enough for me.

**Comment by andywhite37** [comment]
NonEmpty now includes most/all of the extensions currently available.  The Extension concept is still kind of a work in progress, but I think we are moving more in that direction.

**Comment by andywhite37** [comment]
As of 0.12.0, the full set of currently-available extensions should now be available in NonEmpty.

`uncons` doesn't exist yet.

**Comment by andywhite37** [comment]
I added `uncons` in 0.17.0, so I'll close this ticket
